title: watashi
baseurl: /  # default: /
blog_baseurl: /blog
learning_baseurl: /learning
learning_title: \xe3\x81\x82\xe3\x81\xae\xe6\x97\xa5\xe3\x81\xa7\xe3\x81\xbf\xe3\x81\xa1\xe3\x82\x83\xe3\x82\x93\xe3\x81\xa8\xe5\x8b\x89\xe5\xbc\xb7\xe3\x81\x99\xe3\x82\x8b
